title: "Nathaniel Tan"

description: >
  ğŸ“ Singapore
  <br><br>
  Data Analyst in Transition. Iâ€™m pivoting into a data analyst role and using this portfolio to document my projects, growth, and technical skills.
  <br><br>
  <img src="https://img.shields.io/badge/Python-3776AB?logo=python&logoColor=white" alt="Python logo">
  <br><br>
  <img src="https://img.shields.io/badge/SQL-336791?logo=postgresql&logoColor=white" alt="SQL logo">
  <br><br>
  <img src="https://img.shields.io/badge/PowerBI-F2C811?logo=powerbi&logoColor=black" alt="PowerBI logo">
  <br><br>
  <img src="https://img.shields.io/badge/Tableau-E97627?logo=tableau&logoColor=white" alt="Tableau logo">
  <br><br>
  <img src="https://img.shields.io/badge/Excel-217346?logo=microsoftexcel&logoColor=white" alt="Excel logo">
  <br><br>
  ğŸŒ Connect With Me
  <a href="https://www.linkedin.com/in/nathaniel-tanla/"> ğŸ”— LinkedIn </a>
  <a href="https://github.com/nattanla/"> ğŸ’» GitHub </a>

github: false

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

