title: "Nathaniel Tan"
#logo:
description: >
  Exploring data through Python, SQL, and visualisation
  <br><br>
  <a href="https://www.linkedin.com/in/nathaniel-tanla/"> My LinkedIn </a>

theme: jekyll-theme-minimal

