title: "Data Analyst Portfolio | Nathaniel Tan"
description: "Exploring data through Python, SQL, and visualisation."
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache


# Personal Info
name: "Nathaniel Tan"
email: "youremail@example.com"
github_username: yourusername
linkedin_username: yourlinkedin
show_downloads: false
