title: "Nathaniel Tan"

description: >
  üìç Singapore
  <br><br>
  Data Analyst in Transition
  <br><br>
  Exploring data through Python, SQL, and visualisation
  <br><br>
  ![Python](https://img.shields.io/badge/Python-3776AB?logo=python&logoColor=white)
   <br><br>
  ![SQL](https://img.shields.io/badge/SQL-336791?logo=postgresql&logoColor=white)
   <br><br>
  ![PowerBI](https://img.shields.io/badge/PowerBI-F2C811?logo=powerbi&logoColor=black)
   <br><br>
  ![Tableau](https://img.shields.io/badge/Tableau-E97627?logo=tableau&logoColor=white)
   <br><br>
  ![Excel](https://img.shields.io/badge/Excel-217346?logo=microsoftexcel&logoColor=white)
   <br><br>
  üåê Connect With Me
  <br><br>
  <a href="https://www.linkedin.com/in/nathaniel-tanla/"> üîó [LinkedIn] </a>
  <br><br>
  <a href="https://github.com/nattanla/"> üíª [GitHub] </a>




![Python](https://img.shields.io/badge/Python-3776AB?logo=python&logoColor=white)
![SQL](https://img.shields.io/badge/SQL-336791?logo=postgresql&logoColor=white)
![PowerBI](https://img.shields.io/badge/PowerBI-F2C811?logo=powerbi&logoColor=black)
![Tableau](https://img.shields.io/badge/Tableau-E97627?logo=tableau&logoColor=white)
![Excel](https://img.shields.io/badge/Excel-217346?logo=microsoftexcel&logoColor=white)

github: false

theme: jekyll-theme-minimal

