title: "Data Analyst Portfolio | [Nathaniel Tan]"
description: "Exploring data through Python, SQL, and visualisation."
url: "https://nattanla.github.io"
baseurl: ""
gem 'jekyll-include-cache'
plugins:
  - jekyll-include-cache

# Personal Info
name: "[Your Name]"
email: "[youremail@example.com]"
github_username: [yourusername]
linkedin_username: [yourlinkedin]
show_downloads: false

