title: "Nathaniel Tan"
#logo:
description: >
  Exploring data through Python, SQL, and visualisation
  <br><br>
  ## ğŸŒ Connect With Me
  <br><br>
  ğŸ“ Singapore
  <br><br>
  <a href="https://www.linkedin.com/in/nathaniel-tanla/"> ğŸ”— [LinkedIn] </a>
  <br><br>
  <a href="https://github.com/nattanla/"> ğŸ’» [GitHub] </a>

github: false

theme: jekyll-theme-minimal


