title: "Nathaniel Tan"

description: >
  ğŸ“ Singapore
  <br><br>
  Data Analyst in Transition
  <br><br>
  Exploring data through Python, SQL, and visualisation
  <br><br>
  <img src="https://img.shields.io/badge/Python-3776AB?logo=python&logoColor=white" alt="Python logo">
  <br><br>
  <img src="https://img.shields.io/badge/SQL-336791?logo=postgresql&logoColor=white" alt="SQL logo">
  <br><br>
  <img src="https://img.shields.io/badge/PowerBI-F2C811?logo=powerbi&logoColor=black" alt="PowerBI logo">
  <br><br>
  <img src="https://img.shields.io/badge/Tableau-E97627?logo=tableau&logoColor=white" alt="Tableau logo">
  <br><br>
  <img src="https://img.shields.io/badge/Excel-217346?logo=microsoftexcel&logoColor=white" alt="Excel logo">
  <br><br>
  ğŸŒ Connect With Me
  <br><br>
  <a href="https://www.linkedin.com/in/nathaniel-tanla/"> ğŸ”— LinkedIn </a>
  <br><br>
  <a href="https://github.com/nattanla/"> ğŸ’» GitHub </a>

github: false

theme: jekyll-theme-minimal

