title: "Nathaniel Tan"
#logo:
description: >
  Exploring data through Python, SQL, and visualisation
  <br><br>
  ## ğŸŒ Connect With Me
  <br><br>
  ğŸ“ Singapore  
  ğŸ”— [LinkedIn](https://www.linkedin.com/in/nathaniel-tanla)  
  ğŸ’» [GitHub](https://github.com/nattanla)
  <a href="https://www.linkedin.com/in/nathaniel-tanla/"> My LinkedIn </a>

theme: jekyll-theme-minimal

